" Name:         Everblush
" Description:  A dark, vibrant and beautiful colorscheme for Vim
" Author:       Mangeshrex <https://github.com/Mangeshrex>
" Maintainer:   Mangeshrex <https://github.com/Mangeshrex>
" Website:      https://github.com/Everblush/everblush.vim
" License:      Vim License (see `:help license`)
" Last Updated: Tue Jan 24 19:29:49 2023

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'everblush'

let s:t_Co = exists('&t_Co') && !has('gui_running') ? (&t_Co ?? 0) : -1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#232a2d', '#e57474', '#8ccf7e', '#e5c76b', '#67b0e8', '#c47fd5', '#6cbfbf', '#b3b9b8', '#2d3437', '#ef7e7e', '#96d988', '#f4d67a', '#71baf2', '#ce89df', '#67cbe7', '#bdc3c2']
endif
if get(g:, 'everblushNR', 1)
  hi CursorLineNr guifg=#232a2d guibg=NONE gui=NONE cterm=NONE
else
  hi CursorLineNr guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
endif
if get(g:, 'everblush_transp_bg', 0)
  hi Conceal guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffAdd guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi MsgArea guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi MsgSeparator guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi NormalFloat guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalNC guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi Normal guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLine guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi TabLineSel guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
else
  hi Conceal guifg=#67b0e8 guibg=#141b1e gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#141b1e gui=NONE cterm=NONE
  hi DiffAdd guifg=#8ccf7e guibg=#141b1e gui=NONE cterm=NONE
  hi DiffChange guifg=#c47fd5 guibg=#141b1e gui=NONE cterm=NONE
  hi DiffDelete guifg=#6cbfbf guibg=#141b1e gui=NONE cterm=NONE
  hi DiffText guifg=#e57474 guibg=#141b1e gui=NONE cterm=NONE
  hi FoldColumn guifg=#67b0e8 guibg=#141b1e gui=NONE cterm=NONE
  hi Folded guifg=#67b0e8 guibg=#141b1e gui=NONE cterm=NONE
  hi Ignore guifg=#b3b9b8 guibg=#141b1e gui=NONE cterm=NONE
  hi ModeMsg guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi MsgArea guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi MsgSeparator guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi NormalFloat guifg=NONE guibg=#141b1e gui=NONE cterm=NONE
  hi NormalNC guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi Normal guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#141b1e gui=NONE cterm=NONE
  hi StatusLine guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi StatusLineNC guifg=NONE guibg=#141b1e gui=NONE cterm=NONE
  hi TabLineSel guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#141b1e gui=NONE cterm=NONE
endif
hi Boolean guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#71baf2 guibg=NONE gui=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#2d3437 gui=NONE cterm=NONE
hi Comment guifg=#424c50 guibg=NONE gui=italic cterm=italic
hi Conditional guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi Constant guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi Cursor guifg=#dadada guibg=#dadada gui=NONE cterm=NONE
hi CursorIM guifg=#dadada guibg=#dadada gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#232a2d gui=NONE cterm=NONE
hi Debug guifg=#ce89df guibg=NONE gui=NONE cterm=NONE
hi Define guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi Directory guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Error guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#e57474 guibg=#2d3437 gui=NONE cterm=NONE
hi Exception guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi Float guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi FloatBorder guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi IncSearch guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi Label guifg=#71baf2 guibg=NONE gui=NONE cterm=NONE
hi LineNr guifg=#424c50 guibg=NONE gui=NONE cterm=NONE
hi Macro guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi MatchParen guifg=#dadada guibg=#636665 gui=bold cterm=NONE
hi MoreMsg guifg=#67cbe7 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#c47fd5 guibg=#232a2d gui=NONE cterm=NONE
hi Number guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi Operator guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#b3b9b8 guibg=#232a2d gui=NONE cterm=NONE
hi PmenuSel guifg=#2d3437 guibg=#c47fd5 gui=NONE cterm=NONE
hi PmenuThumb guifg=NONE guibg=#8ccf7e gui=NONE cterm=NONE
hi PreCondit guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi Question guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi QuickFixLine guifg=#232a2d guibg=#8ccf7e gui=NONE cterm=NONE
hi Repeat guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=#67b0e8 guibg=#2d3437 gui=NONE cterm=NONE
hi SignColumn guifg=NONE guibg=#232a2d gui=NONE cterm=NONE
hi Special guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#424c50 guibg=NONE gui=italic cterm=italic
hi SpecialKey guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi SpellCap guifg=#e57474 guibg=#2d3437 gui=NONE cterm=NONE
hi SpellLocal guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi SpellRare guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi Storage guifg=#ef7e7e guibg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi Substitute guifg=#e5c76b guibg=#6cbfbf gui=NONE cterm=NONE
hi TabLine guifg=#b3b9b8 guibg=#2d3437 gui=NONE cterm=NONE
hi TabLineFill guifg=NONE guibg=#2d3437 gui=NONE cterm=NONE
hi Tag guifg=#bdc3c2 guibg=NONE gui=NONE cterm=NONE
hi Title guifg=#67b0e8 guibg=NONE gui=bold cterm=bold
hi Todo guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi Typedef guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi Variable guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi VertSplit guifg=#2d3437 guibg=#232a2d gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#232a2d gui=NONE cterm=NONE
hi WarningMsg guifg=#232a2d guibg=NONE gui=NONE cterm=NONE
hi Whitespace guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi WildMenu guifg=#232a2d guibg=#67b0e8 gui=NONE cterm=NONE
hi lCursor guifg=#dadada guibg=#dadada gui=NONE cterm=NONE
hi markdownLinkText guifg=#ef7e7e guibg=NONE gui=NONE cterm=NONE
hi DiagnosticError guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi DiagnosticHint guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi DiagnosticInfo guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi DiagnosticWarn guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi healthError guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi healthSuccess guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi healthWarning guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
if !s:italics
  hi Comment gui=NONE cterm=NONE
  hi SpecialComment gui=NONE cterm=NONE
endif
if get(g:, 'everblush_transp_bg', 0)
  hi LspTroubleNormal guifg=#dadada guibg=NONE gui=NONE cterm=NONE
else
  hi LspTroubleNormal guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
endif
hi LspTroubleCount guifg=#6cbfbf guibg=#dadada gui=NONE cterm=NONE
hi LspTroubleText guifg=#dadada guibg=NONE gui=NONE cterm=NONE
hi illuminatedCurWord guifg=NONE guibg=#dadada gui=NONE cterm=NONE
hi illuminatedWord guifg=NONE guibg=#dadada gui=NONE cterm=NONE
if get(g:, 'everblush_transp_bg', 0)
  hi NeogitDiffAddHighlight guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
  hi NeogitDiffContextHighlight guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi NeogitDiffDeleteHighlight guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
  hi NeogitHunkHeader guifg=#dadada guibg=NONE gui=NONE cterm=NONE
else
  hi NeogitDiffAddHighlight guifg=#67b0e8 guibg=#141b1e gui=NONE cterm=NONE
  hi NeogitDiffContextHighlight guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi NeogitDiffDeleteHighlight guifg=#e57474 guibg=#141b1e gui=NONE cterm=NONE
  hi NeogitHunkHeader guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
endif
hi NeogitBranch guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi NeogitHunkHeaderHighlight guifg=#b3b9b8 guibg=#404749 gui=NONE cterm=NONE
hi NeogitRemote guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
if get(g:, 'everblush_transp_bg', 0)
  hi CmpDocumentationBorder guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi CmpItemAbbr guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi CmpItemAbbrDeprecated guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
  hi CmpItemAbbrMatch guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
  hi CmpItemAbbrMatchFuzzy guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
  hi CmpItemKind guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
  hi CmpItemMenu guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
else
  hi CmpDocumentationBorder guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi CmpItemAbbr guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi CmpItemAbbrDeprecated guifg=#8ccf7e guibg=#141b1e gui=NONE cterm=NONE
  hi CmpItemAbbrMatch guifg=#b3b9b8 guibg=#141b1e gui=NONE cterm=NONE
  hi CmpItemAbbrMatchFuzzy guifg=#b3b9b8 guibg=#141b1e gui=NONE cterm=NONE
  hi CmpItemKind guifg=#67b0e8 guibg=#141b1e gui=NONE cterm=NONE
  hi CmpItemMenu guifg=#8ccf7e guibg=#141b1e gui=NONE cterm=NONE
endif
hi GitGutterAdd guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi GitGutterChange guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi GitGutterDelete guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi GitSignsAdd guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi GitSignsChange guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi GitSignsDelete guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
if get(g:, 'everblush_transp_bg', 0)
  hi TelescopeBorder guifg=#232a2d guibg=NONE gui=NONE cterm=NONE
  hi TelescopeNormal guifg=#dadada guibg=NONE gui=NONE cterm=NONE
else
  hi TelescopeBorder guifg=#232a2d guibg=#141b1e gui=NONE cterm=NONE
  hi TelescopeNormal guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
endif
hi TelescopeSelection guifg=#141b1e guibg=#c47fd5 gui=NONE cterm=NONE
hi IndentBlanklineChar guifg=#232a2d guibg=NONE gui=NONE cterm=NONE
if get(g:, 'everblush_transp_bg', 0)
  hi NvimTreeFolderIcon guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
  hi NvimTreeNormal guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi NvimTreeNormalNC guifg=#dadada guibg=NONE gui=NONE cterm=NONE
  hi NvimTreeStatusLineNC guifg=#141b1e guibg=NONE gui=NONE cterm=NONE
else
  hi NvimTreeFolderIcon guifg=#67b0e8 guibg=#141b1e gui=NONE cterm=NONE
  hi NvimTreeNormal guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi NvimTreeNormalNC guifg=#dadada guibg=#141b1e gui=NONE cterm=NONE
  hi NvimTreeStatusLineNC guifg=#141b1e guibg=#141b1e gui=NONE cterm=NONE
endif
hi NvimTreeEmptyFolderName guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi NvimTreeFolderName guifg=#dadada guibg=NONE gui=NONE cterm=NONE
hi NvimTreeGitDeleted guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi NvimTreeGitDirty guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi NvimTreeGitNew guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi NvimTreeImageFile guifg=#dadada guibg=NONE gui=NONE cterm=NONE
hi NvimTreeIndentMarker guifg=#232a2d guibg=NONE gui=NONE cterm=NONE
hi NvimTreeOpenedFolderName guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi NvimTreeRootFolder guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi NvimTreeSpecialFile guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi NvimTreeSymlink guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
if get(g:, 'everblush_transp_bg', 0)
  hi LspFloatWinNormal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
else
  hi LspFloatWinNormal guifg=NONE guibg=#141b1e gui=NONE cterm=NONE
endif
hi DefinitionCount guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi DefinitionIcon guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi LspFloatWinBorder guifg=#141b1e guibg=NONE gui=NONE cterm=NONE
hi LspSagaBorderTitle guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi LspSagaCodeActionBorder guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi LspSagaCodeActionContent guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi LspSagaCodeActionTitle guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi LspSagaDefPreviewBorder guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi LspSagaFinderSelection guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi LspSagaHoverBorder guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi LspSagaRenameBorder guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi LspSagaSignatureHelpBorder guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi ReferencesCount guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi ReferencesIcon guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TargetWord guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
if get(g:, 'everblush_transp_bg', 0)
  hi BufferLineFill guifg=#141b1e guibg=NONE gui=NONE cterm=NONE
else
  hi BufferLineFill guifg=#141b1e guibg=#141b1e gui=NONE cterm=NONE
endif
hi BufferLineIndicatorSelected guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi TSAttribute guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSBoolean guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi TSCharacter guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSComment guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi TSConditional guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi TSConstBuiltin guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSConstMacro guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi TSConstant guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi TSConstructor guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSDanger guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi TSEmphasis guifg=#b3b9b8 guibg=NONE gui=italic cterm=italic
hi TSEnvironmentName guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi TSEnvirontment guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi TSException guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi TSField guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi TSFloat guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi TSFuncBuiltin guifg=#67cbe7 guibg=NONE gui=NONE cterm=NONE
hi TSFuncMacro guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi TSFunction guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi TSInclude guifg=#ef7e7e guibg=NONE gui=NONE cterm=NONE
hi TSKeyword guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi TSKeywordFunction guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSKeywordReturn guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSLabel guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSLiteral guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi TSMath guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi TSMethod guifg=#71baf2 guibg=NONE gui=NONE cterm=NONE
hi TSNamespace guifg=#ef7e7e guibg=NONE gui=NONE cterm=NONE
hi TSNote guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi TSNumber guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi TSParameter guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi TSParameterReference guifg=#ef7e7e guibg=NONE gui=NONE cterm=NONE
hi TSProperty guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi TSPunctBracket guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSPunctDelimiter guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSPunctSpecial guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSRepeat guifg=#f4d67a guibg=NONE gui=NONE cterm=NONE
hi TSStrike guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSString guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi TSStringEscape guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSStringRegex guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi TSStringSpecial guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSStrong guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSSymbol guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi TSTag guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSTagAttribute guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi TSTagDelimiter guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSText guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSTextReference guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi TSTitle guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi TSType guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi TSTypeBuiltin guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi TSURI guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi TSUnderline guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi TSVariable guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi TSVariableBuiltin guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi TSWarning guifg=#232a2d guibg=#e57474 gui=NONE cterm=NONE
hi TsKeywordOperator guifg=#71baf2 guibg=NONE gui=NONE cterm=NONE
hi PreProcGroup guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi cConstant guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi cCppBracket guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi cCppInElse guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi cCppInElse2 guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi cCppInIf guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi cCppInSkip guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi cCppInWapper guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi cCppOutElse guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi cCppOutIf guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi cCppOutIf2 guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi cCppOutInGroup guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi cCppOutSkip guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi cCppOutWrapper guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi cCppParen guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi cCppString guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi cCurlyError guifg=#b3b9b8 guibg=#ef7e7e gui=NONE cterm=NONE
hi cErrInBracket guifg=#b3b9b8 guibg=#ef7e7e gui=NONE cterm=NONE
hi cErrInParen guifg=#b3b9b8 guibg=#ef7e7e gui=NONE cterm=NONE
hi cFloat guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi cFormat guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi cMutli guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi cOperator guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi cParen guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi cParenError guifg=#b3b9b8 guibg=#ef7e7e gui=NONE cterm=NONE
hi cSpaceError guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi cSpecial guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi cSpecialCharacter guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi cStatement guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi cStorageClass guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi cString guifg=#8ccf7e guibg=NONE gui=NONE cterm=NONE
hi cType guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi cUserCont guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi goBlock guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi goBuiltins guifg=#ce89df guibg=NONE gui=NONE cterm=NONE
hi goCharacter guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi goComment guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi goComplexes guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goConditional guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi goConstants guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi goDecimalInt guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goDeclType guifg=#ce89df guibg=NONE gui=NONE cterm=NONE
hi goDeclaration guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi goDirective guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi goEscapeBigU guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goEscapeC guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goEscapeError guifg=#232a2d guibg=#e57474 gui=NONE cterm=NONE
hi goEscapeOctal guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goEscapeU guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goEscapeX guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goExtraType guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goFloat guifg=#f4d67a guibg=NONE gui=NONE cterm=NONE
hi goFloats guifg=#71baf2 guibg=NONE gui=NONE cterm=NONE
hi goHexadecimalInt guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goImaginary guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goLabel guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goOctalError guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi goOctalInt guifg=#f4d67a guibg=NONE gui=NONE cterm=NONE
hi goParen guifg=#b3b9b8 guibg=NONE gui=NONE cterm=NONE
hi goRawString guifg=#96d988 guibg=NONE gui=NONE cterm=NONE
hi goRepeat guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goSignedInts guifg=#f4d67a guibg=NONE gui=NONE cterm=NONE
hi goSpaceError guifg=#232a2d guibg=#e57474 gui=NONE cterm=NONE
hi goSpecialString guifg=#71baf2 guibg=NONE gui=NONE cterm=NONE
hi goStatement guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi goString guifg=#96d988 guibg=NONE gui=NONE cterm=NONE
hi goTSComment guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi goTSFunction guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goTSInclude guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goTSKeywordFunction guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi goTSMethod guifg=#67b0e8 guibg=NONE gui=NONE cterm=NONE
hi goTSNumber guifg=#2d3437 guibg=NONE gui=NONE cterm=NONE
hi goTSOperator guifg=#71baf2 guibg=NONE gui=NONE cterm=NONE
hi goTSProperty guifg=#e57474 guibg=NONE gui=NONE cterm=NONE
hi goTSPunctBracket guifg=#6cbfbf guibg=NONE gui=NONE cterm=NONE
hi goTSPunctDelimiter guifg=#ce89df guibg=NONE gui=NONE cterm=NONE
hi goTSRepeat guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goTSString guifg=#96d988 guibg=NONE gui=NONE cterm=NONE
hi goTSType guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goTSTypeBuiltin guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goTSVariable guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi goTSkeyword guifg=#c47fd5 guibg=NONE gui=NONE cterm=NONE
hi goTodo guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
hi goType guifg=#e5c76b guibg=NONE gui=NONE cterm=NONE
if !s:italics
  hi TSEmphasis gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'everblushNR', 1)
    hi CursorLineNr ctermfg=235 ctermbg=NONE cterm=NONE
  else
    hi CursorLineNr ctermfg=250 ctermbg=NONE cterm=NONE
  endif
  if get(g:, 'everblush_transp_bg', 0)
    hi Conceal ctermfg=110 ctermbg=NONE cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=114 ctermbg=NONE cterm=NONE
    hi DiffChange ctermfg=176 ctermbg=NONE cterm=NONE
    hi DiffDelete ctermfg=73 ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=174 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=110 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=110 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=250 ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=253 ctermbg=NONE cterm=NONE
    hi MsgArea ctermfg=253 ctermbg=NONE cterm=NONE
    hi MsgSeparator ctermfg=253 ctermbg=NONE cterm=NONE
    hi NormalFloat ctermfg=NONE ctermbg=NONE cterm=NONE
    hi NormalNC ctermfg=253 ctermbg=NONE cterm=NONE
    hi Normal ctermfg=253 ctermbg=NONE cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=253 ctermbg=NONE cterm=NONE
    hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=NONE
    hi TabLineSel ctermfg=253 ctermbg=NONE cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  else
    hi Conceal ctermfg=110 ctermbg=234 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=234 cterm=NONE
    hi DiffAdd ctermfg=114 ctermbg=234 cterm=NONE
    hi DiffChange ctermfg=176 ctermbg=234 cterm=NONE
    hi DiffDelete ctermfg=73 ctermbg=234 cterm=NONE
    hi DiffText ctermfg=174 ctermbg=234 cterm=NONE
    hi FoldColumn ctermfg=110 ctermbg=234 cterm=NONE
    hi Folded ctermfg=110 ctermbg=234 cterm=NONE
    hi Ignore ctermfg=250 ctermbg=234 cterm=NONE
    hi ModeMsg ctermfg=253 ctermbg=234 cterm=NONE
    hi MsgArea ctermfg=253 ctermbg=234 cterm=NONE
    hi MsgSeparator ctermfg=253 ctermbg=234 cterm=NONE
    hi NormalFloat ctermfg=NONE ctermbg=234 cterm=NONE
    hi NormalNC ctermfg=253 ctermbg=234 cterm=NONE
    hi Normal ctermfg=253 ctermbg=234 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=234 cterm=NONE
    hi StatusLine ctermfg=253 ctermbg=234 cterm=NONE
    hi StatusLineNC ctermfg=NONE ctermbg=234 cterm=NONE
    hi TabLineSel ctermfg=253 ctermbg=234 cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=234 cterm=NONE
  endif
  hi Boolean ctermfg=176 ctermbg=NONE cterm=NONE
  hi Character ctermfg=110 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi Comment ctermfg=236 ctermbg=NONE cterm=italic
  hi Conditional ctermfg=174 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=110 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=253 ctermbg=253 cterm=NONE
  hi CursorIM ctermfg=253 ctermbg=253 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi Debug ctermfg=176 ctermbg=NONE cterm=NONE
  hi Define ctermfg=73 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=250 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=110 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=174 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=174 ctermbg=236 cterm=NONE
  hi Exception ctermfg=250 ctermbg=NONE cterm=NONE
  hi Float ctermfg=176 ctermbg=NONE cterm=NONE
  hi FloatBorder ctermfg=114 ctermbg=NONE cterm=NONE
  hi Function ctermfg=110 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=174 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=221 ctermbg=NONE cterm=NONE
  hi Include ctermfg=174 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=176 ctermbg=NONE cterm=NONE
  hi Label ctermfg=110 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=236 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=176 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=174 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=81 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=176 ctermbg=235 cterm=NONE
  hi Number ctermfg=73 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=110 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=250 ctermbg=235 cterm=NONE
  hi PmenuSel ctermfg=236 ctermbg=176 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=114 cterm=NONE
  hi PreCondit ctermfg=176 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=110 ctermbg=NONE cterm=NONE
  hi Question ctermfg=176 ctermbg=NONE cterm=NONE
  hi QuickFixLine ctermfg=NONE ctermbg=114 cterm=NONE
  hi Repeat ctermfg=176 ctermbg=NONE cterm=NONE
  hi Search ctermfg=110 ctermbg=236 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Special ctermfg=110 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=110 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=236 ctermbg=NONE cterm=italic
  hi SpecialKey ctermfg=110 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=174 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=174 ctermbg=236 cterm=NONE
  hi SpellLocal ctermfg=110 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=176 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=176 ctermbg=NONE cterm=NONE
  hi Storage ctermfg=210 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=250 ctermbg=NONE cterm=NONE
  hi String ctermfg=114 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=73 ctermbg=NONE cterm=NONE
  hi Substitute ctermfg=221 ctermbg=73 cterm=NONE
  hi TabLine ctermfg=250 ctermbg=236 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=236 cterm=NONE
  hi Tag ctermfg=251 ctermbg=NONE cterm=NONE
  hi Title ctermfg=110 ctermbg=NONE cterm=bold
  hi Todo ctermfg=176 ctermbg=NONE cterm=NONE
  hi Type ctermfg=110 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=73 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=221 ctermbg=NONE cterm=NONE
  hi Variable ctermfg=176 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=236 ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=235 cterm=NONE
  hi WarningMsg ctermfg=235 ctermbg=NONE cterm=NONE
  hi Whitespace ctermfg=174 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=250 ctermbg=110 cterm=NONE
  hi lCursor ctermfg=253 ctermbg=253 cterm=NONE
  hi markdownLinkText ctermfg=210 ctermbg=NONE cterm=NONE
  hi DiagnosticError ctermfg=174 ctermbg=NONE cterm=NONE
  hi DiagnosticHint ctermfg=114 ctermbg=NONE cterm=NONE
  hi DiagnosticInfo ctermfg=110 ctermbg=NONE cterm=NONE
  hi DiagnosticWarn ctermfg=221 ctermbg=NONE cterm=NONE
  hi healthError ctermfg=174 ctermbg=NONE cterm=NONE
  hi healthSuccess ctermfg=110 ctermbg=NONE cterm=NONE
  hi healthWarning ctermfg=176 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  if get(g:, 'everblush_transp_bg', 0)
    hi LspTroubleNormal ctermfg=253 ctermbg=NONE cterm=NONE
  else
    hi LspTroubleNormal ctermfg=253 ctermbg=234 cterm=NONE
  endif
  hi LspTroubleCount ctermfg=73 ctermbg=253 cterm=NONE
  hi LspTroubleText ctermfg=253 ctermbg=NONE cterm=NONE
  hi illuminatedCurWord ctermfg=NONE ctermbg=253 cterm=NONE
  hi illuminatedWord ctermfg=NONE ctermbg=253 cterm=NONE
  if get(g:, 'everblush_transp_bg', 0)
    hi NeogitDiffAddHighlight ctermfg=110 ctermbg=NONE cterm=NONE
    hi NeogitDiffContextHighlight ctermfg=253 ctermbg=NONE cterm=NONE
    hi NeogitDiffDeleteHighlight ctermfg=174 ctermbg=NONE cterm=NONE
    hi NeogitHunkHeader ctermfg=253 ctermbg=NONE cterm=NONE
  else
    hi NeogitDiffAddHighlight ctermfg=110 ctermbg=234 cterm=NONE
    hi NeogitDiffContextHighlight ctermfg=253 ctermbg=234 cterm=NONE
    hi NeogitDiffDeleteHighlight ctermfg=174 ctermbg=234 cterm=NONE
    hi NeogitHunkHeader ctermfg=253 ctermbg=234 cterm=NONE
  endif
  hi NeogitBranch ctermfg=73 ctermbg=NONE cterm=NONE
  hi NeogitHunkHeaderHighlight ctermfg=250 ctermbg=238 cterm=NONE
  hi NeogitRemote ctermfg=73 ctermbg=NONE cterm=NONE
  if get(g:, 'everblush_transp_bg', 0)
    hi CmpDocumentationBorder ctermfg=253 ctermbg=NONE cterm=NONE
    hi CmpItemAbbr ctermfg=253 ctermbg=NONE cterm=NONE
    hi CmpItemAbbrDeprecated ctermfg=114 ctermbg=NONE cterm=NONE
    hi CmpItemAbbrMatch ctermfg=250 ctermbg=NONE cterm=NONE
    hi CmpItemAbbrMatchFuzzy ctermfg=250 ctermbg=NONE cterm=NONE
    hi CmpItemKind ctermfg=110 ctermbg=NONE cterm=NONE
    hi CmpItemMenu ctermfg=114 ctermbg=NONE cterm=NONE
  else
    hi CmpDocumentationBorder ctermfg=253 ctermbg=234 cterm=NONE
    hi CmpItemAbbr ctermfg=253 ctermbg=234 cterm=NONE
    hi CmpItemAbbrDeprecated ctermfg=114 ctermbg=234 cterm=NONE
    hi CmpItemAbbrMatch ctermfg=250 ctermbg=234 cterm=NONE
    hi CmpItemAbbrMatchFuzzy ctermfg=250 ctermbg=234 cterm=NONE
    hi CmpItemKind ctermfg=110 ctermbg=234 cterm=NONE
    hi CmpItemMenu ctermfg=114 ctermbg=234 cterm=NONE
  endif
  hi GitGutterAdd ctermfg=110 ctermbg=NONE cterm=NONE
  hi GitGutterChange ctermfg=176 ctermbg=NONE cterm=NONE
  hi GitGutterDelete ctermfg=174 ctermbg=NONE cterm=NONE
  hi GitSignsAdd ctermfg=110 ctermbg=NONE cterm=NONE
  hi GitSignsChange ctermfg=176 ctermbg=NONE cterm=NONE
  hi GitSignsDelete ctermfg=174 ctermbg=NONE cterm=NONE
  if get(g:, 'everblush_transp_bg', 0)
    hi TelescopeBorder ctermfg=235 ctermbg=NONE cterm=NONE
    hi TelescopeNormal ctermfg=253 ctermbg=NONE cterm=NONE
  else
    hi TelescopeBorder ctermfg=235 ctermbg=234 cterm=NONE
    hi TelescopeNormal ctermfg=253 ctermbg=234 cterm=NONE
  endif
  hi TelescopeSelection ctermfg=234 ctermbg=176 cterm=NONE
  hi IndentBlanklineChar ctermfg=235 ctermbg=NONE cterm=NONE
  if get(g:, 'everblush_transp_bg', 0)
    hi NvimTreeFolderIcon ctermfg=110 ctermbg=NONE cterm=NONE
    hi NvimTreeNormal ctermfg=253 ctermbg=NONE cterm=NONE
    hi NvimTreeNormalNC ctermfg=253 ctermbg=NONE cterm=NONE
    hi NvimTreeStatusLineNC ctermfg=234 ctermbg=NONE cterm=NONE
  else
    hi NvimTreeFolderIcon ctermfg=110 ctermbg=234 cterm=NONE
    hi NvimTreeNormal ctermfg=253 ctermbg=234 cterm=NONE
    hi NvimTreeNormalNC ctermfg=253 ctermbg=234 cterm=NONE
    hi NvimTreeStatusLineNC ctermfg=234 ctermbg=234 cterm=NONE
  endif
  hi NvimTreeEmptyFolderName ctermfg=114 ctermbg=NONE cterm=NONE
  hi NvimTreeFolderName ctermfg=253 ctermbg=NONE cterm=NONE
  hi NvimTreeGitDeleted ctermfg=174 ctermbg=NONE cterm=NONE
  hi NvimTreeGitDirty ctermfg=176 ctermbg=NONE cterm=NONE
  hi NvimTreeGitNew ctermfg=110 ctermbg=NONE cterm=NONE
  hi NvimTreeImageFile ctermfg=253 ctermbg=NONE cterm=NONE
  hi NvimTreeIndentMarker ctermfg=235 ctermbg=NONE cterm=NONE
  hi NvimTreeOpenedFolderName ctermfg=114 ctermbg=NONE cterm=NONE
  hi NvimTreeRootFolder ctermfg=174 ctermbg=NONE cterm=NONE
  hi NvimTreeSpecialFile ctermfg=73 ctermbg=NONE cterm=NONE
  hi NvimTreeSymlink ctermfg=250 ctermbg=NONE cterm=NONE
  if get(g:, 'everblush_transp_bg', 0)
    hi LspFloatWinNormal ctermfg=NONE ctermbg=NONE cterm=NONE
  else
    hi LspFloatWinNormal ctermfg=NONE ctermbg=234 cterm=NONE
  endif
  hi DefinitionCount ctermfg=73 ctermbg=NONE cterm=NONE
  hi DefinitionIcon ctermfg=250 ctermbg=NONE cterm=NONE
  hi LspFloatWinBorder ctermfg=234 ctermbg=NONE cterm=NONE
  hi LspSagaBorderTitle ctermfg=250 ctermbg=NONE cterm=NONE
  hi LspSagaCodeActionBorder ctermfg=250 ctermbg=NONE cterm=NONE
  hi LspSagaCodeActionContent ctermfg=73 ctermbg=NONE cterm=NONE
  hi LspSagaCodeActionTitle ctermfg=250 ctermbg=NONE cterm=NONE
  hi LspSagaDefPreviewBorder ctermfg=110 ctermbg=NONE cterm=NONE
  hi LspSagaFinderSelection ctermfg=174 ctermbg=NONE cterm=NONE
  hi LspSagaHoverBorder ctermfg=250 ctermbg=NONE cterm=NONE
  hi LspSagaRenameBorder ctermfg=110 ctermbg=NONE cterm=NONE
  hi LspSagaSignatureHelpBorder ctermfg=174 ctermbg=NONE cterm=NONE
  hi ReferencesCount ctermfg=73 ctermbg=NONE cterm=NONE
  hi ReferencesIcon ctermfg=250 ctermbg=NONE cterm=NONE
  hi TargetWord ctermfg=250 ctermbg=NONE cterm=NONE
  if get(g:, 'everblush_transp_bg', 0)
    hi BufferLineFill ctermfg=234 ctermbg=NONE cterm=NONE
  else
    hi BufferLineFill ctermfg=234 ctermbg=234 cterm=NONE
  endif
  hi BufferLineIndicatorSelected ctermfg=114 ctermbg=NONE cterm=NONE
  hi TSAttribute ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSBoolean ctermfg=73 ctermbg=NONE cterm=NONE
  hi TSCharacter ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSComment ctermfg=236 ctermbg=NONE cterm=NONE
  hi TSConditional ctermfg=174 ctermbg=NONE cterm=NONE
  hi TSConstBuiltin ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSConstMacro ctermfg=221 ctermbg=NONE cterm=NONE
  hi TSConstant ctermfg=73 ctermbg=NONE cterm=NONE
  hi TSConstructor ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSDanger ctermfg=236 ctermbg=NONE cterm=NONE
  hi TSEmphasis ctermfg=250 ctermbg=NONE cterm=italic
  hi TSEnvironmentName ctermfg=221 ctermbg=NONE cterm=NONE
  hi TSEnvirontment ctermfg=176 ctermbg=NONE cterm=NONE
  hi TSException ctermfg=236 ctermbg=NONE cterm=NONE
  hi TSField ctermfg=174 ctermbg=NONE cterm=NONE
  hi TSFloat ctermfg=236 ctermbg=NONE cterm=NONE
  hi TSFuncBuiltin ctermfg=81 ctermbg=NONE cterm=NONE
  hi TSFuncMacro ctermfg=114 ctermbg=NONE cterm=NONE
  hi TSFunction ctermfg=174 ctermbg=NONE cterm=NONE
  hi TSInclude ctermfg=210 ctermbg=NONE cterm=NONE
  hi TSKeyword ctermfg=176 ctermbg=NONE cterm=NONE
  hi TSKeywordFunction ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSKeywordReturn ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSLabel ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSLiteral ctermfg=114 ctermbg=NONE cterm=NONE
  hi TSMath ctermfg=73 ctermbg=NONE cterm=NONE
  hi TSMethod ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSNamespace ctermfg=210 ctermbg=NONE cterm=NONE
  hi TSNote ctermfg=236 ctermbg=NONE cterm=NONE
  hi TSNumber ctermfg=221 ctermbg=NONE cterm=NONE
  hi TSParameter ctermfg=174 ctermbg=NONE cterm=NONE
  hi TSParameterReference ctermfg=210 ctermbg=NONE cterm=NONE
  hi TSProperty ctermfg=174 ctermbg=NONE cterm=NONE
  hi TSPunctBracket ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSPunctDelimiter ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSPunctSpecial ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSRepeat ctermfg=222 ctermbg=NONE cterm=NONE
  hi TSStrike ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSString ctermfg=114 ctermbg=NONE cterm=NONE
  hi TSStringEscape ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSStringRegex ctermfg=114 ctermbg=NONE cterm=NONE
  hi TSStringSpecial ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSStrong ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSSymbol ctermfg=174 ctermbg=NONE cterm=NONE
  hi TSTag ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSTagAttribute ctermfg=174 ctermbg=NONE cterm=NONE
  hi TSTagDelimiter ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSText ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSTextReference ctermfg=73 ctermbg=NONE cterm=NONE
  hi TSTitle ctermfg=221 ctermbg=NONE cterm=NONE
  hi TSType ctermfg=221 ctermbg=NONE cterm=NONE
  hi TSTypeBuiltin ctermfg=221 ctermbg=NONE cterm=NONE
  hi TSURI ctermfg=221 ctermbg=NONE cterm=NONE
  hi TSUnderline ctermfg=176 ctermbg=NONE cterm=NONE
  hi TSVariable ctermfg=250 ctermbg=NONE cterm=NONE
  hi TSVariableBuiltin ctermfg=110 ctermbg=NONE cterm=NONE
  hi TSWarning ctermfg=235 ctermbg=174 cterm=NONE
  hi TsKeywordOperator ctermfg=110 ctermbg=NONE cterm=NONE
  hi PreProcGroup ctermfg=110 ctermbg=NONE cterm=NONE
  hi cConstant ctermfg=110 ctermbg=NONE cterm=NONE
  hi cCppBracket ctermfg=250 ctermbg=NONE cterm=NONE
  hi cCppInElse ctermfg=250 ctermbg=NONE cterm=NONE
  hi cCppInElse2 ctermfg=250 ctermbg=NONE cterm=NONE
  hi cCppInIf ctermfg=110 ctermbg=NONE cterm=NONE
  hi cCppInSkip ctermfg=250 ctermbg=NONE cterm=NONE
  hi cCppInWapper ctermfg=176 ctermbg=NONE cterm=NONE
  hi cCppOutElse ctermfg=250 ctermbg=NONE cterm=NONE
  hi cCppOutIf ctermfg=236 ctermbg=NONE cterm=NONE
  hi cCppOutIf2 ctermfg=236 ctermbg=NONE cterm=NONE
  hi cCppOutInGroup ctermfg=236 ctermbg=NONE cterm=NONE
  hi cCppOutSkip ctermfg=236 ctermbg=NONE cterm=NONE
  hi cCppOutWrapper ctermfg=176 ctermbg=NONE cterm=NONE
  hi cCppParen ctermfg=250 ctermbg=NONE cterm=NONE
  hi cCppString ctermfg=114 ctermbg=NONE cterm=NONE
  hi cCurlyError ctermfg=250 ctermbg=210 cterm=NONE
  hi cErrInBracket ctermfg=250 ctermbg=210 cterm=NONE
  hi cErrInParen ctermfg=250 ctermbg=210 cterm=NONE
  hi cFloat ctermfg=236 ctermbg=NONE cterm=NONE
  hi cFormat ctermfg=110 ctermbg=NONE cterm=NONE
  hi cMutli ctermfg=221 ctermbg=NONE cterm=NONE
  hi cOperator ctermfg=110 ctermbg=NONE cterm=NONE
  hi cParen ctermfg=221 ctermbg=NONE cterm=NONE
  hi cParenError ctermfg=250 ctermbg=210 cterm=NONE
  hi cSpaceError ctermfg=174 ctermbg=NONE cterm=NONE
  hi cSpecial ctermfg=110 ctermbg=NONE cterm=NONE
  hi cSpecialCharacter ctermfg=110 ctermbg=NONE cterm=NONE
  hi cStatement ctermfg=176 ctermbg=NONE cterm=NONE
  hi cStorageClass ctermfg=221 ctermbg=NONE cterm=NONE
  hi cString ctermfg=114 ctermbg=NONE cterm=NONE
  hi cType ctermfg=221 ctermbg=NONE cterm=NONE
  hi cUserCont ctermfg=250 ctermbg=NONE cterm=NONE
  hi goBlock ctermfg=250 ctermbg=NONE cterm=NONE
  hi goBuiltins ctermfg=176 ctermbg=NONE cterm=NONE
  hi goCharacter ctermfg=174 ctermbg=NONE cterm=NONE
  hi goComment ctermfg=236 ctermbg=NONE cterm=NONE
  hi goComplexes ctermfg=221 ctermbg=NONE cterm=NONE
  hi goConditional ctermfg=176 ctermbg=NONE cterm=NONE
  hi goConstants ctermfg=176 ctermbg=NONE cterm=NONE
  hi goDecimalInt ctermfg=221 ctermbg=NONE cterm=NONE
  hi goDeclType ctermfg=176 ctermbg=NONE cterm=NONE
  hi goDeclaration ctermfg=176 ctermbg=NONE cterm=NONE
  hi goDirective ctermfg=174 ctermbg=NONE cterm=NONE
  hi goEscapeBigU ctermfg=110 ctermbg=NONE cterm=NONE
  hi goEscapeC ctermfg=110 ctermbg=NONE cterm=NONE
  hi goEscapeError ctermfg=235 ctermbg=174 cterm=NONE
  hi goEscapeOctal ctermfg=110 ctermbg=NONE cterm=NONE
  hi goEscapeU ctermfg=110 ctermbg=NONE cterm=NONE
  hi goEscapeX ctermfg=110 ctermbg=NONE cterm=NONE
  hi goExtraType ctermfg=221 ctermbg=NONE cterm=NONE
  hi goFloat ctermfg=222 ctermbg=NONE cterm=NONE
  hi goFloats ctermfg=110 ctermbg=NONE cterm=NONE
  hi goHexadecimalInt ctermfg=221 ctermbg=NONE cterm=NONE
  hi goImaginary ctermfg=221 ctermbg=NONE cterm=NONE
  hi goLabel ctermfg=221 ctermbg=NONE cterm=NONE
  hi goOctalError ctermfg=174 ctermbg=NONE cterm=NONE
  hi goOctalInt ctermfg=222 ctermbg=NONE cterm=NONE
  hi goParen ctermfg=250 ctermbg=NONE cterm=NONE
  hi goRawString ctermfg=114 ctermbg=NONE cterm=NONE
  hi goRepeat ctermfg=221 ctermbg=NONE cterm=NONE
  hi goSignedInts ctermfg=222 ctermbg=NONE cterm=NONE
  hi goSpaceError ctermfg=235 ctermbg=174 cterm=NONE
  hi goSpecialString ctermfg=110 ctermbg=NONE cterm=NONE
  hi goStatement ctermfg=174 ctermbg=NONE cterm=NONE
  hi goString ctermfg=114 ctermbg=NONE cterm=NONE
  hi goTSComment ctermfg=236 ctermbg=NONE cterm=NONE
  hi goTSFunction ctermfg=110 ctermbg=NONE cterm=NONE
  hi goTSInclude ctermfg=110 ctermbg=NONE cterm=NONE
  hi goTSKeywordFunction ctermfg=176 ctermbg=NONE cterm=NONE
  hi goTSMethod ctermfg=110 ctermbg=NONE cterm=NONE
  hi goTSNumber ctermfg=236 ctermbg=NONE cterm=NONE
  hi goTSOperator ctermfg=110 ctermbg=NONE cterm=NONE
  hi goTSProperty ctermfg=174 ctermbg=NONE cterm=NONE
  hi goTSPunctBracket ctermfg=73 ctermbg=NONE cterm=NONE
  hi goTSPunctDelimiter ctermfg=176 ctermbg=NONE cterm=NONE
  hi goTSRepeat ctermfg=221 ctermbg=NONE cterm=NONE
  hi goTSString ctermfg=114 ctermbg=NONE cterm=NONE
  hi goTSType ctermfg=221 ctermbg=NONE cterm=NONE
  hi goTSTypeBuiltin ctermfg=221 ctermbg=NONE cterm=NONE
  hi goTSVariable ctermfg=176 ctermbg=NONE cterm=NONE
  hi goTSkeyword ctermfg=176 ctermbg=NONE cterm=NONE
  hi goTodo ctermfg=221 ctermbg=NONE cterm=NONE
  hi goType ctermfg=221 ctermbg=NONE cterm=NONE
  if !s:italics
    hi TSEmphasis cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: color0     #232a2d ~
" Color: color1     #e57474 ~
" Color: color2     #8ccf7e ~
" Color: color3     #e5c76b ~
" Color: color4     #67b0e8 ~
" Color: color5     #c47fd5 ~
" Color: color6     #6cbfbf ~
" Color: color7     #b3b9b8 ~
" Color: color8     #2d3437 ~
" Color: color9     #ef7e7e ~
" Color: color10    #96d988 ~
" Color: color11    #f4d67a ~
" Color: color12    #71baf2 ~
" Color: color13    #ce89df ~
" Color: color14    #67cbe7 ~
" Color: color15    #bdc3c2 ~
" Color: background #141b1e ~
" Color: foreground #dadada ~
" Color: comment    #404749 ~
" Term colors: color0  color1  color2  color3
" Term colors: color4  color5  color6  color7
" Term colors: color8  color9  color10 color11
" Term colors: color12 color13 color14 color15
" vim: et ts=2 sw=2
